import {useEffect,useState} from "react";
import {Search,Download,Folder,RefreshCw,HardDrive,ExternalLink} from "lucide-react";
type Result={title:string;size:number;seeders:number;leechers:number;magnetUrl:string;infoUrl?:string;guid?:string};
const bytes=(n:number)=>{if(!n)return"0 B";const u=["B","KB","MB","GB","TB"];const i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return(n/1024**i).toFixed(i?1:0)+" "+u[i]};
const request=async(path:string,init?:RequestInit)=>{const r=await fetch(path,init);const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw Error(d?.detail||d?.error||t||r.statusText);return d};
export default function App(){
 const[q,setQ]=useState("The Last of Us"),[results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(false),[quota,setQuota]=useState<any>(null),[task,setTask]=useState<any>(null),[files,setFiles]=useState<any[]>([]),[error,setError]=useState("");
 const load=async()=>{try{setQuota(await request("/api/seedr/quota"));const f=await request("/api/seedr/files");setFiles(f.files||[]);const t=await request("/api/seedr/tasks");if(t.tasks?.length)setTask(t.tasks[0])}catch(e:any){setError(e.message)}};
 const search=async()=>{if(!q.trim())return;setLoading(true);setError("");try{setResults(await request("/api/search?q="+encodeURIComponent(q)))}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!task?.id)return;const timer=setInterval(async()=>{try{const x=await request("/api/seedr/tasks/"+task.id);setTask(x.task);if(x.status==="completed"){clearInterval(timer);load()}}catch{}},3000);return()=>clearInterval(timer)},[task?.id]);
 const add=async(r:Result)=>{setError("");try{const x=await request("/api/seedr/add",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({magnet:r.magnetUrl})});setTask(x);await load()}catch(e:any){setError(e.message)}};
 return <div className="min-h-screen bg-slate-950 text-slate-100"><main className="max-w-5xl mx-auto p-5 space-y-5">
 <header className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">SeedFlow</h1><p className="text-sm text-slate-400">Lightweight Render · 1337x → Seedr</p></div>{quota&&<div className="text-right text-xs"><div className="flex items-center gap-2"><HardDrive className="w-4 h-4"/>{bytes(quota.remainingSpace)} free</div><div className="text-slate-500">{bytes(quota.usedSpace)} / {bytes(quota.maxSpace)}</div></div>}</header>
 <form onSubmit={e=>{e.preventDefault();search()}} className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} className="flex-1 rounded-xl bg-slate-900 border border-slate-700 px-4 py-3 outline-none" placeholder="Search torrents"/><button className="px-5 rounded-xl bg-cyan-500 text-slate-950 font-bold">{loading?<RefreshCw className="animate-spin"/>:<Search/>}</button></form>
 {error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}
 {task&&<section className="rounded-2xl border border-cyan-500/20 bg-slate-900 p-4"><div className="flex justify-between"><b>{task.title||"Seedr download"}</b><span>{task.progress??0}%</span></div><div className="h-2 bg-slate-800 rounded-full mt-3 overflow-hidden"><div className="h-full bg-cyan-500" style={{width:(task.progress??0)+"%"}}/></div><p className="text-xs text-slate-500 mt-2">{task.state||"processing"}</p></section>}
 <section className="space-y-2">{results.map(r=><article key={r.guid||r.magnetUrl} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="font-semibold">{r.title}</div><div className="text-xs text-slate-400 mt-2">{bytes(r.size)} · ↑ {r.seeders} · ↓ {r.leechers}</div><div className="flex gap-2 mt-3"><button onClick={()=>add(r)} className="px-3 py-2 rounded-lg bg-cyan-500 text-slate-950 text-sm font-bold flex items-center gap-2"><Download className="w-4 h-4"/>Send to Seedr</button>{r.infoUrl&&<a href={r.infoUrl} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-lg bg-slate-800 text-sm"><ExternalLink className="w-4 h-4 inline mr-1"/>Source</a>}</div></article>)}</section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold flex items-center gap-2"><Folder className="w-4 h-4"/>My Cloud Files</h2>{files.length?<div className="mt-3 space-y-2">{files.map((f:any)=><div key={f.id} className="flex justify-between text-sm border-t border-slate-800 pt-2"><span>{f.name}</span><span className="text-slate-500">{bytes(f.size)}</span></div>)}</div>:<p className="text-sm text-slate-500 mt-3">No files yet.</p>}</section>
 </main></div>
}